version: 2
updates:
  - package-ecosystem: mix
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    target-branch: master
    labels:
      - "dependencies"
      - "mix"
  - package-ecosystem: npm
    directory: "/assets"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    target-branch: master
    labels:
      - "dependencies"
      - "npm"
  - package-ecosystem: github-actions
    schedule:
      interval: monthly
    target-branch: master
    labels:
      - "dependencies"
      - "dependabot"
